#Delivery Pipeline for our clusters

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: gitops
description: main application pipeline
serialPipeline:
  stages:
  - targetId: qsdev
  - targetId: qsprod
---

#Our 1st Cluster TARGET
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster:  projects/$PROJECT_ID/locations/asia-southeast1/clusters/autopilot-cluster-mind-test
executionConfigs:
- defaultPool:
    serviceAccount: gke-clouddeploy-sa@$PROJECT_ID.iam.gserviceaccount.com
  usages:
  - RENDER 
  - DEPLOY   
---
#Our 2st Cluster TARGET

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsprod
description: production cluster
requireApproval: true
gke:
 cluster:  projects/$PROJECT_ID/locations/asia-southeast1/clusters/autopilot-cluster-mind-prod
executionConfigs:
- defaultPool:
    serviceAccount: gke-clouddeploy-s@$PROJECT_ID.iam.gserviceaccount.com
  usages:
  - RENDER 
  - DEPLOY