steps:
# Build and tag using commit sha
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/mind-artifact/nginx-image:${COMMIT_SHA}', '-f', 'Dockerfile']
# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/mind-artifact/nginx-image:${COMMIT_SHA}']
# Create release in Google Cloud Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "gitops",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "mind-artifact/nginx-image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/mind-artifact/nginx-image:${COMMIT_SHA}"
    ]