# Build and tag using commit sha

steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'asia-southeast1-docker.pkg.dev/devops-sandbox-2023/mind-artifact/nginx-image:${COMMIT_SHA}', '-f', 'Dockerfile']


# Push the container image


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast1-docker.pkg.dev/devops-sandbox-2023/mind-artifact/nginx-image:${COMMIT_SHA}']

- name: ubuntu
  args:
  - sed
  - "-i"
  - s~<VERSION>~${COMMIT_SHA}~
  - "deployment.yaml"

- name: 'gcr.io/cloud-builders/git'
  args: ['add', '.']

- name: 'gcr.io/cloud-builders/git'
  args: ['commit', '-m', 'update']

- name: 'gcr.io/cloud-builders/git'
  args: ['push', '--all', 'origin'] 

# Create release in Google Cloud Deploy

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "gitops",
      "--region", "asia-southeast1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "nginx-image=asia-southeast1-docker.pkg.dev/devops-sandbox-2023/mind-artifact/nginx-image:${COMMIT_SHA}" 
      ]

