apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    app.kubernetes.io/managed-by: google-cloud-deploy
    deploy.cloud.google.com/delivery-pipeline-id: gitops
    deploy.cloud.google.com/location: asia-southeast1
    deploy.cloud.google.com/project-id: devops-sandbox-2023
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/managed-by: google-cloud-deploy
        deploy.cloud.google.com/delivery-pipeline-id: gitops
        deploy.cloud.google.com/location: asia-southeast1
        deploy.cloud.google.com/project-id: devops-sandbox-2023
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/devops-sandbox-2023/mind-artifact/nginx-image
          name: nginx
          ports:
            - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: google-cloud-deploy
    deploy.cloud.google.com/delivery-pipeline-id: gitops
    deploy.cloud.google.com/location: asia-southeast1
    deploy.cloud.google.com/project-id: devops-sandbox-2023
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
