apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: git-ops
build:
  artifacts:
  - image: gcr.io/devops-sandbox-2023/nginx-image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml