apiVersion: skaffold/v4beta7
Kind: Config
metadata:
  name: git-ops
build:
  artifacts:
  - image: asia-southeast1-docker.pkg.dev/devops-sandbox-2023/mind-artifact/nginx-image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml