apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: git-ops
build:
  artifacts:
  - image: asia-southeast1-docker.pkg.dev/devops-sandbox-2023/mind-artifact/nginx-image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-manifests/deployment.yaml