apiVersion: skaffold/v3alpha1
kind: Config
deploy:
  kubectl: {}
profiles:
- name: qsdev
  manifests:
    rawYaml:
    - deployment.yaml
- name: qsprod
  manifests:
    rawYaml:
    - deployment.yaml
